languageCode = "ja"
languageName = "日本語"
weight = 1
title = "SSBlog"

[params]
  displayName = "JA"
  isoCode = "ja"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/ssblog_logo.png"
  secondaryLogo = "img/secondary-logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
name = "Choco Park"
image = "img/author.jpg"
headline = "Coding, creativity, and life – join me on this journey!"
bio = "A little bit about me"
links = [
  { email = "mailto:espoir618@gmail.com" },
  { github = "https://github.com/PARK-SUNGJUN-618" }
]